[custom]
;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=💻 Github,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/realbokeliu/boke/main/clashroyaleapp.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📹 TikTok,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/tiktok.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Spotify.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/realbokeliu/boke/main/supercell.list
ruleset=🎮 HLTV,https://raw.githubusercontent.com/realbokeliu/boke/main/hltv.list
ruleset=🤖 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Claude.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎮 Twitch,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitch/Twitch.list
ruleset=📹 bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📹 bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=💻 Github`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📹 Youtube`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎮 Twitch`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📹 bilibili`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点
custom_proxy_group=📹 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎵 Spotify`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=🎮 HLTV`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]♻️ 自动选择`[]🚀 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🇮🇳 印度节点`[]🇷🇺 俄罗斯节点`[]🇦🇺 澳大利亚节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇲🇴 澳门节点`[]🇦🇷 阿根廷节点`[]🇹🇷 土耳其节点`[]🇧🇷 巴西节点`[]🇮🇪 爱尔兰节点`[]🇰🇵 朝鲜节点`[]🇦🇶 南极节点`[]📱 自建节点`[]🚀 手动切换
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(韩国|韩|KR|Korea)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|美国)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇮🇳 印度节点`url-test`(印度|IN|India|孟买|新德里|班加罗尔)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇷🇺 俄罗斯节点`url-test`(俄罗斯|RU|Russia)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇺 澳大利亚节点`url-test`(澳大利亚|AU|Australia)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇦 加拿大节点`url-test`(加拿大|CA|Canada)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国节点`url-test`(英国|UK|United Kingdom)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇫🇷 法国节点`url-test`(法国|FR|France)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国节点`url-test`(德国|Germany)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇴 澳门节点`url-test`(澳门|Macao)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇷 阿根廷节点`url-test`(阿根廷|AR|Argentina)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇷 土耳其节点`url-test`(土耳其|Turkey)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇧🇷 巴西节点`url-test`(巴西|BR|Brazil)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇪 爱尔兰节点`url-test`(爱尔兰|Ireland)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇵 朝鲜节点`url-test`(朝鲜|平壤)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇶 南极节点`url-test`(南极)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📱 自建节点`select`(自建|bokeliu)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
